[book]
authors = ["Pierre Beucher"]
language = "en"
multilingual = false
src = "src"
title = "Crafteo - Docker Training"

[output.html]
git-repository-url = "https://github.com/PierreBeucher/docker.training.crafteo.io"